services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: sh -c "npm run prisma:deploy && npm run dev"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://nodeflow:nodeflow@postgres:5432/nodeflow?schema=public
      REDIS_URL: redis://redis:6379
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
      target: build
    command: npm run dev:worker
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://nodeflow:nodeflow@postgres:5432/nodeflow?schema=public
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nodeflow
      POSTGRES_PASSWORD: nodeflow
      POSTGRES_DB: nodeflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nodeflow -d nodeflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6385:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
